package com.cqkct.FunKidII.db.Entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.support.annotation.IntDef;
import android.text.TextUtils;

import com.cqkct.FunKidII.Bean.BaseBean;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Keep;

import java.io.Serializable;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.NotNull;

/**
 * Entity mapped to table CHAT_BEAN.
 */

@Entity
public class ChatEntity implements BaseBean, Serializable {

    private static final long serialVersionUID = 7833861621553484656L;
    @Id(autoincrement = true)
    private Long id;

    /**
     * 这条消息对应的 APP 用户
     */
    @NotNull
    private String userId;

    /**
     * 这条消息对应的设备
     * <p>
     *     设备单聊时，不能为空；家庭群聊时可能为空。
     * </p>
     */
    private String deviceId;

    /**
     * 聊天群ID
     */
    private String groupId;

    /**
     * 消息发送者ID。消息由谁发送。即 from 。接受的消息表示对方；发送的消息表示自己。
     */
    @NotNull
    private String senderId;
    /**
     * 发送者类型。取值参考 {@link protocol.Message.TermAddr.Type}
     * @see protocol.Message.TermAddr.Type#USER
     * @see protocol.Message.TermAddr.Type#DEVICE
     */
    private int senderType;

    /**
     * 消息时间戳。单位：毫秒
     */
    private long timestamp;

    /**
     * 是否是向外发送的消息
     */
    private boolean isSendDir;

    /**
     * 消息发送状态
     */
    @SendStatus
    private int sendStatus;
    /**
     * 正在发送
     */
    public static final int SEND_STAT_QUEUE = 0;
    /**
     * 发送成功
     */
    public static final int SEND_STAT_SENT = 1;
    /**
     * 发送失败
     */
    public static final int SEND_STAT_FAILED = 2;
    @IntDef({SEND_STAT_QUEUE, SEND_STAT_SENT, SEND_STAT_FAILED})
    @Retention(RetentionPolicy.SOURCE)
    public @interface SendStatus {}

    /**
     * 消息是否已显示过
     */
    private boolean isSeen;

    /**
     * 消息类型。文本还是语音还是表情
     */
    @MessageType
    private int messageType;
    public static final int TYPE_TEXT = 0;
    public static final int TYPE_VOICE = 1;
    public static final int TYPE_EMOTICON = 2;
    @IntDef({TYPE_VOICE, TYPE_EMOTICON, TYPE_TEXT})
    @Retention(RetentionPolicy.SOURCE)
    public @interface MessageType {}

    /**
     * 文本消息
     */
    private String text;

    /**
     * 语音/图片 文件名
     */
    private String filename;
    /**
     * 语音/图片 文件大小
     */
    private long fileSize;

    /**
     * 语音时长，单位：秒
     */
    private int voiceDuration;
    /**
     * 语音文件是否已播放
     * <p>
     *     与 isSeen 不一样。isSeen 标记消息是否已经显示过。
     * </p>
     */
    private boolean voiceIsPlayed;

    /**
     * 图片 宽度
     */
    private int imageWidth;
    /**
     * 图片 高度
     */
    private int imageHeight;

    /**
     * 文件已上传状态
     */
    @FileUploadStatus
    private int fileUploadStatus;
    /**
     * 从未上传，或上传失败
     */
    public static final int FILE_UPLOAD_NONE = 0;
    /**
     * 正在上传
     */
    public static final int FILE_UPLOAD_PROGRESS = 1;
    /**
     * 上传成功
     */
    public static final int FILE_UPLOAD_SUCCESS = 2;
    @IntDef({FILE_UPLOAD_NONE, FILE_UPLOAD_PROGRESS, FILE_UPLOAD_SUCCESS})
    @Retention(RetentionPolicy.SOURCE)
    public @interface FileUploadStatus {}

    /**
     * 表情消息
     */
    private String emoticon;


    @Generated(hash = 1511800348)
    public ChatEntity(Long id, @NotNull String userId, String deviceId, String groupId,
            @NotNull String senderId, int senderType, long timestamp, boolean isSendDir, int sendStatus,
            boolean isSeen, int messageType, String text, String filename, long fileSize,
            int voiceDuration, boolean voiceIsPlayed, int imageWidth, int imageHeight,
            int fileUploadStatus, String emoticon) {
        this.id = id;
        this.userId = userId;
        this.deviceId = deviceId;
        this.groupId = groupId;
        this.senderId = senderId;
        this.senderType = senderType;
        this.timestamp = timestamp;
        this.isSendDir = isSendDir;
        this.sendStatus = sendStatus;
        this.isSeen = isSeen;
        this.messageType = messageType;
        this.text = text;
        this.filename = filename;
        this.fileSize = fileSize;
        this.voiceDuration = voiceDuration;
        this.voiceIsPlayed = voiceIsPlayed;
        this.imageWidth = imageWidth;
        this.imageHeight = imageHeight;
        this.fileUploadStatus = fileUploadStatus;
        this.emoticon = emoticon;
    }

    @Generated(hash = 2143846278)
    public ChatEntity() {
    }


    // KEEP
    @Override
    @Keep
    public Long getId() {
        return id;
    }

    @Keep
    public @SendStatus int getSendStatus() {
        return this.sendStatus;
    }

    @Keep
    public void setSendStatus(@SendStatus int sendStatus) {
        this.sendStatus = sendStatus;
    }

    @Keep
    public @MessageType int getMessageType() {
        return this.messageType;
    }

    @Keep
    public void setMessageType(@MessageType int messageType) {
        this.messageType = messageType;
    }

    @Keep
    public @FileUploadStatus int getFileUploadStatus() {
        return this.fileUploadStatus;
    }

    @Keep
    public void setFileUploadStatus(@FileUploadStatus int fileUploadStatus) {
        this.fileUploadStatus = fileUploadStatus;
    }

    @Keep
    public boolean isGroup() {
        return !TextUtils.isEmpty(getGroupId());
    }
    // KEEP END

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getDeviceId() {
        return this.deviceId;
    }

    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    public String getGroupId() {
        return this.groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public String getSenderId() {
        return this.senderId;
    }

    public void setSenderId(String senderId) {
        this.senderId = senderId;
    }

    public int getSenderType() {
        return this.senderType;
    }

    public void setSenderType(int senderType) {
        this.senderType = senderType;
    }

    public long getTimestamp() {
        return this.timestamp;
    }

    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    public boolean getIsSendDir() {
        return this.isSendDir;
    }

    public void setIsSendDir(boolean isSendDir) {
        this.isSendDir = isSendDir;
    }

    public boolean getIsSeen() {
        return this.isSeen;
    }

    public void setIsSeen(boolean isSeen) {
        this.isSeen = isSeen;
    }

    public String getText() {
        return this.text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getFilename() {
        return this.filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    public long getFileSize() {
        return this.fileSize;
    }

    public void setFileSize(long fileSize) {
        this.fileSize = fileSize;
    }

    public int getVoiceDuration() {
        return this.voiceDuration;
    }

    public void setVoiceDuration(int voiceDuration) {
        this.voiceDuration = voiceDuration;
    }

    public boolean getVoiceIsPlayed() {
        return this.voiceIsPlayed;
    }

    public void setVoiceIsPlayed(boolean voiceIsPlayed) {
        this.voiceIsPlayed = voiceIsPlayed;
    }

    public int getImageWidth() {
        return this.imageWidth;
    }

    public void setImageWidth(int imageWidth) {
        this.imageWidth = imageWidth;
    }

    public int getImageHeight() {
        return this.imageHeight;
    }

    public void setImageHeight(int imageHeight) {
        this.imageHeight = imageHeight;
    }

    public String getEmoticon() {
        return this.emoticon;
    }

    public void setEmoticon(String emoticon) {
        this.emoticon = emoticon;
    }
}
