package com.cqkct.FunKidII.db.Entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.cqkct.FunKidII.Bean.BaseBean;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Keep;
import org.greenrobot.greendao.annotation.NotNull;

import java.io.Serializable;

/**
 * Entity mapped to table NOTIFY_MESSAGE_BEAN.
 */
@Entity
public class NotifyMessageEntity implements BaseBean, Serializable {

    private static final long serialVersionUID = 3235336764507258778L;
    @Id(autoincrement = true)
    private Long id;
    @NotNull
    private String userId;
    @NotNull
    private String deviceId;
    @NotNull
    private long time;
    @NotNull
    private int Tag;
    @NotNull
    private byte[] data;
    /**
     * 消息内容类型，参考 MessageCenterUtils 里的常量定义
     */
    @NotNull
    private int contentType;

    private String deviceName;

    private String originator;
    private String originator_phone;
    private String originator_relation;
    private String seq; //流水号 仅绑定请求时使用

    private boolean isRead;


    @Generated(hash = 1826169935)
    public NotifyMessageEntity(Long id, @NotNull String userId, @NotNull String deviceId, long time,
            int Tag, @NotNull byte[] data, int contentType, String deviceName, String originator,
            String originator_phone, String originator_relation, String seq, boolean isRead) {
        this.id = id;
        this.userId = userId;
        this.deviceId = deviceId;
        this.time = time;
        this.Tag = Tag;
        this.data = data;
        this.contentType = contentType;
        this.deviceName = deviceName;
        this.originator = originator;
        this.originator_phone = originator_phone;
        this.originator_relation = originator_relation;
        this.seq = seq;
        this.isRead = isRead;
    }


    @Generated(hash = 2147441526)
    public NotifyMessageEntity() {
    }


    // KEEP METHODS - put your custom methods here
    @Override
    @Keep
    public Long getId() {
        return id;
    }
    // KEEP METHODS END


    public void setId(Long id) {
        this.id = id;
    }


    public String getUserId() {
        return this.userId;
    }


    public void setUserId(String userId) {
        this.userId = userId;
    }


    public String getDeviceId() {
        return this.deviceId;
    }


    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }


    public long getTime() {
        return this.time;
    }


    public void setTime(long time) {
        this.time = time;
    }


    public int getTag() {
        return this.Tag;
    }


    public void setTag(int Tag) {
        this.Tag = Tag;
    }


    public byte[] getData() {
        return this.data;
    }


    public void setData(byte[] data) {
        this.data = data;
    }


    public int getContentType() {
        return this.contentType;
    }


    public void setContentType(int contentType) {
        this.contentType = contentType;
    }


    public String getDeviceName() {
        return this.deviceName;
    }


    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName;
    }


    public String getOriginator() {
        return this.originator;
    }


    public void setOriginator(String originator) {
        this.originator = originator;
    }


    public String getOriginator_phone() {
        return this.originator_phone;
    }


    public void setOriginator_phone(String originator_phone) {
        this.originator_phone = originator_phone;
    }


    public String getOriginator_relation() {
        return this.originator_relation;
    }


    public void setOriginator_relation(String originator_relation) {
        this.originator_relation = originator_relation;
    }


    public String getSeq() {
        return this.seq;
    }


    public void setSeq(String seq) {
        this.seq = seq;
    }


    public boolean getIsRead() {
        return this.isRead;
    }


    public void setIsRead(boolean isRead) {
        this.isRead = isRead;
    }

}
